version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  authenticate:
    build: ./authenticate
    ports:
      - "3001:3000"
    networks:
      - app-network

  cart:
    build: ./cart
    ports:
      - "3002:3000"
    networks:
      - app-network

  items:
    build: ./items
    ports:
      - "3003:3000"
    networks:
      - app-network

  order:
    build: ./order
    ports:
      - "3004:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
